/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.MystStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MystStandaloneSetup extends MystStandaloneSetupGenerated {
  public static void doSetup() {
    new MystStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
