/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.ide;

import org.xtext.example.mydsl.ide.AbstractMystIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MystIdeModule extends AbstractMystIdeModule {
}
