/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.MystRuntimeModule;
import org.xtext.example.mydsl.MystStandaloneSetup;
import org.xtext.example.mydsl.ide.MystIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MystIdeSetup extends MystStandaloneSetup {
  @Override
  public Injector createInjector() {
    MystRuntimeModule _mystRuntimeModule = new MystRuntimeModule();
    MystIdeModule _mystIdeModule = new MystIdeModule();
    return Guice.createInjector(Modules2.mixin(_mystRuntimeModule, _mystIdeModule));
  }
}
