/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.myst;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Calcul</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myst.Calcul#getStrategy <em>Strategy</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myst.Calcul#getAlgorithm <em>Algorithm</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myst.MystPackage#getCalcul()
 * @model
 * @generated
 */
public interface Calcul extends EObject
{
  /**
   * Returns the value of the '<em><b>Strategy</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Strategy</em>' containment reference.
   * @see #setStrategy(Strategy)
   * @see org.xtext.example.mydsl.myst.MystPackage#getCalcul_Strategy()
   * @model containment="true"
   * @generated
   */
  Strategy getStrategy();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myst.Calcul#getStrategy <em>Strategy</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Strategy</em>' containment reference.
   * @see #getStrategy()
   * @generated
   */
  void setStrategy(Strategy value);

  /**
   * Returns the value of the '<em><b>Algorithm</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.myst.Algorithm}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Algorithm</em>' attribute.
   * @see org.xtext.example.mydsl.myst.Algorithm
   * @see #setAlgorithm(Algorithm)
   * @see org.xtext.example.mydsl.myst.MystPackage#getCalcul_Algorithm()
   * @model
   * @generated
   */
  Algorithm getAlgorithm();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myst.Calcul#getAlgorithm <em>Algorithm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Algorithm</em>' attribute.
   * @see org.xtext.example.mydsl.myst.Algorithm
   * @see #getAlgorithm()
   * @generated
   */
  void setAlgorithm(Algorithm value);

} // Calcul
