/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.myst;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cross Validation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myst.CrossValidation#getMotcle <em>Motcle</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myst.MystPackage#getCrossValidation()
 * @model
 * @generated
 */
public interface CrossValidation extends EObject
{
  /**
   * Returns the value of the '<em><b>Motcle</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Motcle</em>' attribute.
   * @see #setMotcle(String)
   * @see org.xtext.example.mydsl.myst.MystPackage#getCrossValidation_Motcle()
   * @model
   * @generated
   */
  String getMotcle();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myst.CrossValidation#getMotcle <em>Motcle</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Motcle</em>' attribute.
   * @see #getMotcle()
   * @generated
   */
  void setMotcle(String value);

} // CrossValidation
