/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.myst;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CSV</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myst.CSV#getCvsfile <em>Cvsfile</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myst.MystPackage#getCSV()
 * @model
 * @generated
 */
public interface CSV extends EObject
{
  /**
   * Returns the value of the '<em><b>Cvsfile</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cvsfile</em>' attribute.
   * @see #setCvsfile(String)
   * @see org.xtext.example.mydsl.myst.MystPackage#getCSV_Cvsfile()
   * @model
   * @generated
   */
  String getCvsfile();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myst.CSV#getCvsfile <em>Cvsfile</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cvsfile</em>' attribute.
   * @see #getCvsfile()
   * @generated
   */
  void setCvsfile(String value);

} // CSV
