/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.myst;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Metric</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myst.MystPackage#getMetric()
 * @model
 * @generated
 */
public enum Metric implements Enumerator
{
  /**
   * The '<em><b>Accuracy</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ACCURACY_VALUE
   * @generated
   * @ordered
   */
  ACCURACY(0, "Accuracy", "showAccuracy"),

  /**
   * The '<em><b>Recall</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RECALL_VALUE
   * @generated
   * @ordered
   */
  RECALL(1, "Recall", "showRecall"),

  /**
   * The '<em><b>Measure</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MEASURE_VALUE
   * @generated
   * @ordered
   */
  MEASURE(2, "Measure", "showFMeasure"),

  /**
   * The '<em><b>Precision</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PRECISION_VALUE
   * @generated
   * @ordered
   */
  PRECISION(3, "Precision", "showPrecision"),

  /**
   * The '<em><b>Balanced Accuracy Score</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BALANCED_ACCURACY_SCORE_VALUE
   * @generated
   * @ordered
   */
  BALANCED_ACCURACY_SCORE(4, "BalancedAccuracyScore", "showBalancedAccuracyScore"),

  /**
   * The '<em><b>Hamming Loss</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HAMMING_LOSS_VALUE
   * @generated
   * @ordered
   */
  HAMMING_LOSS(5, "HammingLoss", "showHammingLoss"),

  /**
   * The '<em><b>Jaccard Score</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JACCARD_SCORE_VALUE
   * @generated
   * @ordered
   */
  JACCARD_SCORE(6, "JaccardScore", "showJaccardScore"),

  /**
   * The '<em><b>Matthews Corr Coef</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MATTHEWS_CORR_COEF_VALUE
   * @generated
   * @ordered
   */
  MATTHEWS_CORR_COEF(7, "matthewsCorrCoef", "showMatthewsCorrCoef"),

  /**
   * The '<em><b>Zero One Loss</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ZERO_ONE_LOSS_VALUE
   * @generated
   * @ordered
   */
  ZERO_ONE_LOSS(8, "ZeroOneLoss", "showZeroOneLoss");

  /**
   * The '<em><b>Accuracy</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ACCURACY
   * @model name="Accuracy" literal="showAccuracy"
   * @generated
   * @ordered
   */
  public static final int ACCURACY_VALUE = 0;

  /**
   * The '<em><b>Recall</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RECALL
   * @model name="Recall" literal="showRecall"
   * @generated
   * @ordered
   */
  public static final int RECALL_VALUE = 1;

  /**
   * The '<em><b>Measure</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MEASURE
   * @model name="Measure" literal="showFMeasure"
   * @generated
   * @ordered
   */
  public static final int MEASURE_VALUE = 2;

  /**
   * The '<em><b>Precision</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PRECISION
   * @model name="Precision" literal="showPrecision"
   * @generated
   * @ordered
   */
  public static final int PRECISION_VALUE = 3;

  /**
   * The '<em><b>Balanced Accuracy Score</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BALANCED_ACCURACY_SCORE
   * @model name="BalancedAccuracyScore" literal="showBalancedAccuracyScore"
   * @generated
   * @ordered
   */
  public static final int BALANCED_ACCURACY_SCORE_VALUE = 4;

  /**
   * The '<em><b>Hamming Loss</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HAMMING_LOSS
   * @model name="HammingLoss" literal="showHammingLoss"
   * @generated
   * @ordered
   */
  public static final int HAMMING_LOSS_VALUE = 5;

  /**
   * The '<em><b>Jaccard Score</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JACCARD_SCORE
   * @model name="JaccardScore" literal="showJaccardScore"
   * @generated
   * @ordered
   */
  public static final int JACCARD_SCORE_VALUE = 6;

  /**
   * The '<em><b>Matthews Corr Coef</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MATTHEWS_CORR_COEF
   * @model name="matthewsCorrCoef" literal="showMatthewsCorrCoef"
   * @generated
   * @ordered
   */
  public static final int MATTHEWS_CORR_COEF_VALUE = 7;

  /**
   * The '<em><b>Zero One Loss</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ZERO_ONE_LOSS
   * @model name="ZeroOneLoss" literal="showZeroOneLoss"
   * @generated
   * @ordered
   */
  public static final int ZERO_ONE_LOSS_VALUE = 8;

  /**
   * An array of all the '<em><b>Metric</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Metric[] VALUES_ARRAY =
    new Metric[]
    {
      ACCURACY,
      RECALL,
      MEASURE,
      PRECISION,
      BALANCED_ACCURACY_SCORE,
      HAMMING_LOSS,
      JACCARD_SCORE,
      MATTHEWS_CORR_COEF,
      ZERO_ONE_LOSS,
    };

  /**
   * A public read-only list of all the '<em><b>Metric</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Metric> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Metric</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Metric get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Metric result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Metric</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Metric getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Metric result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Metric</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Metric get(int value)
  {
    switch (value)
    {
      case ACCURACY_VALUE: return ACCURACY;
      case RECALL_VALUE: return RECALL;
      case MEASURE_VALUE: return MEASURE;
      case PRECISION_VALUE: return PRECISION;
      case BALANCED_ACCURACY_SCORE_VALUE: return BALANCED_ACCURACY_SCORE;
      case HAMMING_LOSS_VALUE: return HAMMING_LOSS;
      case JACCARD_SCORE_VALUE: return JACCARD_SCORE;
      case MATTHEWS_CORR_COEF_VALUE: return MATTHEWS_CORR_COEF;
      case ZERO_ONE_LOSS_VALUE: return ZERO_ONE_LOSS;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Metric(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Metric
