/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.myst;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parse</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myst.Parse#getVariableCible <em>Variable Cible</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myst.MystPackage#getParse()
 * @model
 * @generated
 */
public interface Parse extends EObject
{
  /**
   * Returns the value of the '<em><b>Variable Cible</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable Cible</em>' attribute.
   * @see #setVariableCible(String)
   * @see org.xtext.example.mydsl.myst.MystPackage#getParse_VariableCible()
   * @model
   * @generated
   */
  String getVariableCible();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myst.Parse#getVariableCible <em>Variable Cible</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable Cible</em>' attribute.
   * @see #getVariableCible()
   * @generated
   */
  void setVariableCible(String value);

} // Parse
