/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.myst;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myst.Program#getCsv <em>Csv</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myst.Program#getParse <em>Parse</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myst.Program#getCalcul <em>Calcul</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myst.Program#getMetric <em>Metric</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myst.MystPackage#getProgram()
 * @model
 * @generated
 */
public interface Program extends EObject
{
  /**
   * Returns the value of the '<em><b>Csv</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Csv</em>' containment reference.
   * @see #setCsv(CSV)
   * @see org.xtext.example.mydsl.myst.MystPackage#getProgram_Csv()
   * @model containment="true"
   * @generated
   */
  CSV getCsv();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myst.Program#getCsv <em>Csv</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Csv</em>' containment reference.
   * @see #getCsv()
   * @generated
   */
  void setCsv(CSV value);

  /**
   * Returns the value of the '<em><b>Parse</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parse</em>' containment reference.
   * @see #setParse(Parse)
   * @see org.xtext.example.mydsl.myst.MystPackage#getProgram_Parse()
   * @model containment="true"
   * @generated
   */
  Parse getParse();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myst.Program#getParse <em>Parse</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parse</em>' containment reference.
   * @see #getParse()
   * @generated
   */
  void setParse(Parse value);

  /**
   * Returns the value of the '<em><b>Calcul</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Calcul</em>' containment reference.
   * @see #setCalcul(Calcul)
   * @see org.xtext.example.mydsl.myst.MystPackage#getProgram_Calcul()
   * @model containment="true"
   * @generated
   */
  Calcul getCalcul();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myst.Program#getCalcul <em>Calcul</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Calcul</em>' containment reference.
   * @see #getCalcul()
   * @generated
   */
  void setCalcul(Calcul value);

  /**
   * Returns the value of the '<em><b>Metric</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.myst.Metric}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Metric</em>' attribute.
   * @see org.xtext.example.mydsl.myst.Metric
   * @see #setMetric(Metric)
   * @see org.xtext.example.mydsl.myst.MystPackage#getProgram_Metric()
   * @model
   * @generated
   */
  Metric getMetric();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myst.Program#getMetric <em>Metric</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Metric</em>' attribute.
   * @see org.xtext.example.mydsl.myst.Metric
   * @see #getMetric()
   * @generated
   */
  void setMetric(Metric value);

} // Program
