/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.myst;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Training Test</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myst.TrainingTest#getTestRate <em>Test Rate</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myst.MystPackage#getTrainingTest()
 * @model
 * @generated
 */
public interface TrainingTest extends EObject
{
  /**
   * Returns the value of the '<em><b>Test Rate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Test Rate</em>' attribute.
   * @see #setTestRate(double)
   * @see org.xtext.example.mydsl.myst.MystPackage#getTrainingTest_TestRate()
   * @model
   * @generated
   */
  double getTestRate();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myst.TrainingTest#getTestRate <em>Test Rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Test Rate</em>' attribute.
   * @see #getTestRate()
   * @generated
   */
  void setTestRate(double value);

} // TrainingTest
